---
- name: kubeflow
  hosts: master1
  gather_facts: no
 
  vars:
    ansible_become_pass: "ccma"

  tasks:
    # ks
    - name: Download ksonnet
      get_url: 
        url: https://github.com/ksonnet/releases/download/v0.13.1/ks_0.13.1_linux_amd64.tar.gz
        dest: /tmp/ks_0.13.1_linux_amd64.tar.gz
        validate_certs: no 

    - name: Create the bin directory if it does not exist
      file:
        path: /home/ccma/bin
        state: directory
        mode: 0755

    - name: Extract ks file
      unarchive: 
        src: /tmp/ks_0.13.1_linux_amd64.tar.gz
        dest: /home/ccma/bin/
        remote_src: yes

    # kubeflow
    - name: Create the kubeflow directory if it does not exist
      file:
        path: /home/ccma/kubeflow
        state: directory
        mode: 0755

    - name: Download kubeflow
      get_url: 
        url: https://github.com/kubeflow/kubeflow/releases/download/v0.5.1/kfctl_v0.5.1_linux.tar.gz
        dest: /tmp/kfctl_v0.5.1_linux.tar.gz
        validate_certs: no 

    - name: Extract kubeflow file
      unarchive: 
        src: /tmp/kfctl_v0.5.1_linux.tar.gz
        dest: /home/ccma/kubeflow/
        remote_src: yes

    - name: update the PATH variable
      become: yes
      lineinfile:
        dest: /etc/environment
        state: present
        backrefs: yes
        regexp: 'PATH=(["]*)((?!.*?/home/ccma/kubeflow/).*?)(["]*)$'
        line: 'PATH=\1\2:/home/ccma/kubeflow/\3'

    - name: Setup and deploy kubeflow
      become: yes
      shell: "kfctl init kfapp"
      environment:
        PATH: "/home/ccma/bin/ks_0.13.1_linux_amd64:/home/ccma/.kube/config:/home/ccma/kubeflow"
      args:
        chdir: /home/ccma/kubeflow
      register: deploy_kubeflow 

    - name: Debug deploy_kubeflow 
      debug:
        var: deploy_kubeflow 
 
    - name: kfctl_generate
      become: yes
      shell: "kfctl generate all -V"
      environment:
        PATH: "/home/ccma/bin/ks_0.13.1_linux_amd64:/home/ccma/.kube/config:/home/ccma/kubeflow"
      args:
        chdir: /home/ccma/kubeflow/kfapp
      register: kfctl_generate

    - name: Debug kfctl_generate
      debug:
        var: kfctl_generate

    - name: kfctl_apply
      become: yes
      shell: "kfctl apply all -V"
      environment:
        PATH: "/home/ccma/bin/ks_0.13.1_linux_amd64:/home/ccma/.kube/config:/home/ccma/kubeflow"
      args:
        chdir: /home/ccma/kubeflow/kfapp
      register: kfctl_apply

    - name: Debug kfctl_apply
      debug:
        var: kfctl_apply

    # Deploy PyTorch
    - name: Deploy PyTorch
      become: yes
      shell: "ks apply default -c pytorch-operator"
      environment:
        PATH: "/home/ccma/bin/ks_0.13.1_linux_amd64:/home/ccma/.kube/config:/home/ccma/kubeflow"
      args:
        chdir: /home/ccma/kubeflow/kfapp/ks_app
      register: deploy_pytorch

    - name: Debug deploy_pytorch
      debug:
        var: deploy_pytorch

    # Setup PersistentVolume
    - name: Copy storage.yml to remote
      copy: 
        src: storage.yml
        dest: /home/ccma/kubeflow/kfapp/storage.yml
        owner: ccma
        group: ccma
        mode: 0644

    - name: Run kubectl create --filename storage.yml
      become: yes
      shell: "kubectl create --filename storage.yml"
      environment:
        KUBECONFIG: /home/ccma/.kube/config
      args:
        chdir: /home/ccma/kubeflow/kfapp
      register: create_storage

    - name: Debug create_storage
      debug:
        var: create_storage
